### ISSUE TITLE
Anchor style is not implemented

### ISSUE THREAD

**Issue by pmatulis** [canonical-webteam-archive/vanilla-docs-theme#44]
Moved from: https://github.com/ubuntudesign/vanilla-docs-theme-design/issues/4 as reported by @evilnick 

>> The API documentation no longer has anchors. Without anchors its impossible to point someone to an API endpoint when they ask a question. I can only give them the page and then they have to search for it. Anchor links allow us to give a link that auto scrolls to the correct location.

> The anchor class is generated correctly from the docs, but isn't implemented in the style

**Comment by kwm14** [comment]
Moved from: https://github.com/ubuntudesign/vanilla-docs-theme-design/issues/4 as reported by @anthonydillon 

>The ids are created for the TOC on the right-hand side. That said we should create an anchor pattern and have the documentation-builder add a link to the headings to utilise the anchor link.

Updating status labels on bug based on review.
